name: clang-format
on:
  pull_request:
    branches:
      - main
    paths:
      - '**.cpp'
      - '**.hpp'
  push:
    branches:
      - main
    paths:
      - '**.cpp'
      - '**.hpp'
  workflow_dispatch:
jobs:
  format:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: |
          find "engine" "projects" -type f \( -name "*.cpp" -o -name "*.hpp" \) | xargs clang-format -Werror --dry-run
